# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gearbox
      POSTGRES_PASSWORD: gearbox
      POSTGRES_DB: gearbox_dev
    ports:
      - '5432:5432'
